//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azmoun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colibrations
    {
        public int Id { get; set; }
        public string Certificate_Number { get; set; }
        public System.DateTime Date_of_Calibration { get; set; }
        public string Customer_name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Re_Calibration_Date { get; set; }
        public string Location { get; set; }
        public string Form_number { get; set; }
        public string Calibration_Condition { get; set; }
    
        public virtual Instruments_category Instruments_category { get; set; }
    }
}
