//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azmoun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruments_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instruments_category()
        {
            this.Colibrations = new HashSet<Colibrations>();
        }
    
        public int Device_id { get; set; }
        public string Device_category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colibrations> Colibrations { get; set; }
        public virtual Presure_device Presure_device { get; set; }
    }
}
