//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azmoun
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzmounEntities : DbContext
    {
        public AzmounEntities()
            : base("name=AzmounEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Colibrations> Colibrations { get; set; }
        public virtual DbSet<Instruments_category> Instruments_category { get; set; }
        public virtual DbSet<Presure_device> Presure_device { get; set; }
        public virtual DbSet<Refrences> Refrences { get; set; }
    }
}
