//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azmoun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presure_device
    {
        public int Id { get; set; }
        public string Device_type { get; set; }
        public string Device_name { get; set; }
        public string Mode { get; set; }
        public Nullable<int> Class { get; set; }
        public double Min_range { get; set; }
        public double Max_range { get; set; }
        public double Resulation { get; set; }
        public string Serial_number { get; set; }
        public string Manufacturer { get; set; }
        public string Reception_Number { get; set; }
    
        public virtual Instruments_category Instruments_category { get; set; }
    }
}
