//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azmoun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refrences
    {
        public int Id { get; set; }
        public string category { get; set; }
        public string Name { get; set; }
        public string Range_unit { get; set; }
        public Nullable<double> Min_range { get; set; }
        public Nullable<double> Max_range { get; set; }
        public string Accuracy_unit { get; set; }
        public double Accuracy { get; set; }
    }
}
